compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

pnpEnableEsmLoader: true

globalFolder: ../.yarn/berry

packageExtensions:
  ts-jest@*:
    dependencies:
      jest: '*'
      typescript: 4.6.2
  '@atls-ui-parts/text@*':
    dependencies:
      '@types/styled-system': '*'
  '@emotion/utils@*':
    dependencies:
      '@emotion/sheet': '*'
preferReuse: true

yarnPath: .yarn/releases/yarn.cjs
