compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

pnpEnableEsmLoader: true

globalFolder: ../.yarn/berry

packageExtensions:
  ts-jest@*:
    dependencies:
      jest: '*'
      typescript: 4.6.2

preferReuse: true

yarnPath: .yarn/releases/yarn.cjs
