compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@atls-ui-parts/text@*':
    dependencies:
      '@types/styled-system': '*'
  '@emotion/utils@*':
    dependencies:
      '@emotion/sheet': '*'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
